set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER mips-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER mips-linux-gnu-g++)
#set(CMAKE_FIND_ROOT_PATH "/home/jwzhang/work/aip/custom/gcc720-glibc229-fp64-r517-0705")
option(MIPS "Enable MIPS" ON)
